- name: Install collectd
  yum: name={{item}} state=installed
  with_items:
    - collectd

- name: configure collectd.conf
  template: src={{item}}.j2 dest=/etc/{{item}}
  sudo: yes
  with_items:
    - collectd.conf

- name: Start collectd after reboot
  shell: "/sbin/chkconfig --add {{item}}"
  sudo: yes
  with_items:
    - collectd

- name: Start collectd
  service: name=collectd state=started
  sudo: yes

