# Run this on IPA Server
- name: add client to dns
  shell: ipa dnsrecord-add {{ ".".join(ansible_fqdn.split(".")[1:]) }} {{ hostvars[item]["ansible_hostname"] }} --a-rec {{hostvars[item]["ansible_"+hostvars[item].interface]['ipv4']['address']}}
  sudo: yes
  with_items: groups['IPAClient']
  register: command_result
  ignore_errors: True

# todo
# loop through command_result
# if not (item.rc == 1 and "ipa: ERROR: no modifications to be performed" != item.stderr ) error out.

#- fail: msg=command_result.stderr
#- command: >
    #{% if item.rc == 0 %}
      #/bin/true;
    #{% elif item.rc ==1 and  "ipa: ERROR: no modifications to be performed" != item.stderr %}
      #/bin/true;
    #{% else %}
      #/bin/false;
    #{% endif %}
  #with_items:
    #command_result.results




