- name: yum install nrpe related packages
  yum: name={{ item }}
  sudo: yes
  with_items:
    - nrpe
    - nagios-plugins-all
    - nagios-plugins-nrpe

- name: symlink /usr/lib64/nagios/ to /usr/lib/nagios
  file: src="/usr/lib64/nagios" dest="/usr/lib/nagios" state=link
  sudo: yes

# The disk_info will be used in nrpe.cfg
- name: get disk info
  command: df /
  register: disk_info
- debug: var=disk_info.stdout_lines[1:] # skip the header

- name: copy check_memory
  copy: src={{ item }} dest=/usr/lib64/nagios/plugins/{{ item }} mode=755
  sudo: yes
  with_items:
    - check_memory

- name: setup nrpe.cfg
  template: src={{ item }}.j2 dest=/etc/nagios/{{ item }}
  sudo: yes
  with_items:
    - nrpe.cfg

- name: chown root:shinken /usr/lib64/nagios/plugins
  shell: chown -R root:shinken /usr/lib64/nagios/plugins
  sudo: yes

- name: chmod u+s /usr/lib64/nagios/plugins/*
  shell: chmod u+s /usr/lib64/nagios/plugins/*
  sudo: yes

- name: run nrpe automatically at boot time
  command: /sbin/chkconfig nrpe on
  sudo: yes

- name: start nrpe
  service: name=nrpe state=started
  sudo: yes
