kafka_jmx_port: 9010
kafka_heap_opts: -Xmx3072M -Xms3072M
kafka_conf_dir: /etc/kafka/conf
log_dir: /var/log/kafka
kafka_version: 2.9.2-0.8.1.1
kafka_home: /usr/lib/kafka_{{kafka_version}}
kafka_num_partitions: 2
replica_fetch_max_bytes: 7295552
