- name: install easy_install for python
  yum: name={{item}} state=installed
  sudo: yes
  with_items:
    - libffi-devel
    - mysql-server
    - mysql-devel
    - python-devel
    - python-setuptools
    - nginx
    - libpng-devel
    - zlib-devel
    - libXrender-devel
    - fontconfig-devel
    - pixman
    - pixman-devel

- easy_install: name=pip
  sudo: yes

- name: download cairo's source
  get_url: url=http://cairographics.org/releases/cairo-1.10.0.tar.gz dest=/tmp/cairo-1.10.0.tar.gz

- name: untar cairo source
  shell: tar xvzf /tmp/cairo-1.10.0.tar.gz
  args:
    chdir: /tmp

- shell: ./configure --prefix=/usr/lib/cairo
  sudo: yes
  args:
    chdir: /tmp/cairo-1.10.0

- shell: make
  sudo: yes
  args:
    chdir: /tmp/cairo-1.10.0

- shell: make install
  sudo: yes
  args:
    chdir: /tmp/cairo-1.10.0

- name: downlaod pycairo's source
  get_url: url=http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2 dest=/tmp/py2cairo-1.10.0.tar.bz2

- name: untar pycairo source
  shell: tar xvjf /tmp/py2cairo-1.10.0.tar.bz2
  args:
    chdir: /tmp

- shell: PKG_CONFIG_PATH=/usr/lib/cairo/lib/pkgconfig ./waf configure
  args:
    chdir: /tmp/py2cairo-1.10.0

- shell: ./waf build
  args:
    chdir: /tmp/py2cairo-1.10.0

- shell: ./waf install
  sudo: yes
  args:
    chdir: /tmp/py2cairo-1.10.0

- name: install dependencies
  pip: name={{item}} version=1.6
  sudo: yes
  with_items:
    - Django

- name: install dependencies
  pip: name={{item}}
  sudo: yes
  with_items:
    - django-tagging
    - pytz
    - uwsgi
    - MySQL-python
    - cairocffi

- pip: name=https://github.com/graphite-project/ceres/tarball/master
  sudo: yes

- pip: name=whisper
  sudo: yes

- pip: name=carbon extra_args='--install-option="--install-scripts=/usr/bin" --install-option="--install-lib=/usr/lib/python2.6/site-packages" --install-option="--install-data=/var/lib/graphite"'
  sudo: yes


- pip: name=graphite-web extra_args='--install-option="--install-scripts=/usr/bin" --install-option="--install-lib=/usr/lib/python2.6/site-packages" --install-option="--install-data=/var/lib/graphite"'
  sudo: yes

- shell: cp /var/lib/graphite/conf/{{item}}.example /var/lib/graphite/conf/{{item}}
  sudo: yes
  with_items:
    - carbon.conf
    - storage-schemas.conf
    - storage-aggregation.conf
    - aggregation-rules.conf

- name: configure local)settings.py
  template: src={{ item }}.j2 dest=/usr/lib/python2.6/site-packages/graphite/{{item}}
  sudo: yes
  with_items:
    - local_settings.py.j2

- name: create database
  mysql_db: name={{db_name}} state=present
  sudo: yes

# sudo carbon-aggregator.py --config=/var/lib/graphite/conf/carbon.conf start
# sudo carbon-cache.py --config=/var/lib/graphite/conf/carbon.conf start
