# TODO: take to Zab about what gid and uid have already been taken.
- name: Ensure that shinken group exists
  sudo: yes
  group: name=shinken state=present gid=1000

- name: Ensure that shinken user exists
  sudo: yes
  user: group=shinken name=shinken state=present uid=1000

- name: Install necessary yum packages
  yum: name={{item}} state=installed
  sudo: yes
  with_items:
    - python-pycurl
    - python-setuptools
    - python-pip

- name: install shinken
  sudo: yes
  pip: name=shinken state=present

- name: initialize shinken cli
  sudo_user: shinken
  shell: "shinken --init"

- name: install various shinken modules
  sudo_user: shinken
  shell: "shinken install {{item}}"
  with_items:
    - webui
    - auth-cfg-password

- template: src={{item}}.j2 dest=/etc/shinken/modules/{{item}}
  sudo: yes
  with_items:
    - webui.cfg

- template: src={{item}}.j2 dest=/etc/shinken/brokers/{{item}}
  sudo: yes
  with_items:
    - broker-master.cfg

- name: Ensure that shinken is running after reboot
  sudo: yes
  shell: /sbin/chkconfig shinken on

- name: run shinken
  sudo: yes
  service: name=shinken state=started


